### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [garyravago/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by garyravago** [comment]
Hi Michael,
Thanks for the prompt feedback!  Yeah, I thought something didn't look right when I looked at this on my iPhone but did check out some testing websites for viewing mobile devices where it did appear right.
I went ahead and googled the meta tag and added the viewport meta tag into my application.html file and now it looks great!  Appreciate the support.

**Comment by Mikeysax** [comment]
:+1:
